"""Add VAPI-like columns to AgentConfig part 2

Revision ID: bbf25bb3c633
Revises: 492f7296aff8
Create Date: 2026-04-07 15:12:08.464168+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf25bb3c633'
down_revision: Union[str, None] = '492f7296aff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('template', sa.String(length=50), nullable=False),
    sa.Column('first_message', sa.Text(), nullable=False),
    sa.Column('first_message_mode', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('stt_provider', sa.String(length=50), nullable=False),
    sa.Column('stt_model', sa.String(length=100), nullable=True),
    sa.Column('stt_language', sa.String(length=20), nullable=False),
    sa.Column('transcriber_keywords', sa.Text(), nullable=True),
    sa.Column('fallback_transcribers', sa.Text(), nullable=True),
    sa.Column('tts_provider', sa.String(length=50), nullable=False),
    sa.Column('tts_model', sa.String(length=100), nullable=True),
    sa.Column('tts_voice', sa.String(length=50), nullable=True),
    sa.Column('tts_language', sa.String(length=20), nullable=False),
    sa.Column('tts_pitch', sa.Float(), nullable=False),
    sa.Column('tts_pace', sa.Float(), nullable=False),
    sa.Column('tts_loudness', sa.Float(), nullable=False),
    sa.Column('tts_stability', sa.Float(), nullable=False),
    sa.Column('tts_clarity', sa.Float(), nullable=False),
    sa.Column('tts_speed', sa.Float(), nullable=False),
    sa.Column('tts_style', sa.Float(), nullable=False),
    sa.Column('tts_use_speaker_boost', sa.Integer(), nullable=False),
    sa.Column('tts_optimize_streaming_latency', sa.Integer(), nullable=False),
    sa.Column('tts_input_preprocessing', sa.Integer(), nullable=False),
    sa.Column('tts_filler_injection', sa.Integer(), nullable=False),
    sa.Column('add_voice_manually', sa.String(length=255), nullable=True),
    sa.Column('fallback_voices', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('llm_temperature', sa.Float(), nullable=False),
    sa.Column('max_response_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_max_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_emotion_recognition', sa.Integer(), nullable=False),
    sa.Column('silence_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('background_sound', sa.String(length=50), nullable=False),
    sa.Column('background_denoising', sa.Integer(), nullable=False),
    sa.Column('model_output_in_realtime', sa.Integer(), nullable=False),
    sa.Column('record_calls', sa.Integer(), nullable=False),
    sa.Column('recording_consent_plan', sa.String(length=50), nullable=True),
    sa.Column('voicemail_detection_enabled', sa.Integer(), nullable=False),
    sa.Column('voicemail_message', sa.Text(), nullable=True),
    sa.Column('end_call_phrases', sa.Text(), nullable=True),
    sa.Column('end_call_message', sa.Text(), nullable=True),
    sa.Column('summary_enabled', sa.Integer(), nullable=False),
    sa.Column('success_evaluation_enabled', sa.Integer(), nullable=False),
    sa.Column('structured_output_enabled', sa.Integer(), nullable=False),
    sa.Column('tools_enabled', sa.Text(), nullable=True),
    sa.Column('predefined_functions', sa.Text(), nullable=True),
    sa.Column('custom_functions', sa.Text(), nullable=True),
    sa.Column('keypad_input_enabled', sa.Integer(), nullable=False),
    sa.Column('keypad_timeout', sa.Integer(), nullable=False),
    sa.Column('sms_enabled', sa.Integer(), nullable=False),
    sa.Column('sms_provider', sa.String(length=50), nullable=True),
    sa.Column('sms_message_template', sa.Text(), nullable=True),
    sa.Column('hipaa_enabled', sa.Integer(), nullable=False),
    sa.Column('pii_redaction_enabled', sa.Integer(), nullable=False),
    sa.Column('telephony_option', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('ai_number', sa.String(length=30), nullable=True),
    sa.Column('sip_provider', sa.String(length=50), nullable=True),
    sa.Column('sip_account_sid', sa.String(length=255), nullable=True),
    sa.Column('sip_auth_token', sa.String(length=255), nullable=True),
    sa.Column('sip_domain', sa.String(length=255), nullable=True),
    sa.Column('livekit_url', sa.String(length=255), nullable=True),
    sa.Column('livekit_api_key', sa.String(length=255), nullable=True),
    sa.Column('livekit_api_secret', sa.String(length=255), nullable=True),
    sa.Column('existing_clinic_number', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_configs_status'), 'agent_configs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_configs_tenant_id'), 'agent_configs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_configs_tenant_id'), table_name='agent_configs')
    op.drop_index(op.f('ix_agent_configs_status'), table_name='agent_configs')
    op.drop_table('agent_configs')
    # ### end Alembic commands ###
