"""Add VAPI-like columns to AgentConfig

Revision ID: 492f7296aff8
Revises: 1a2b3c4d5e6f
Create Date: 2026-04-07 15:05:38.432203+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492f7296aff8'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_name', sa.String(length=255), nullable=False),
    sa.Column('admin_name', sa.String(length=255), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_password', sa.String(length=100), nullable=True),
    sa.Column('ai_number', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_number')
    )
    op.create_table('call_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=100), nullable=False),
    sa.Column('caller_phone', sa.String(length=30), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('detected_lang', sa.String(length=10), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('transcript_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_call_id'), 'call_logs', ['call_id'], unique=True)
    op.create_index(op.f('ix_call_logs_outcome'), 'call_logs', ['outcome'], unique=False)
    op.create_index(op.f('ix_call_logs_tenant_id'), 'call_logs', ['tenant_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('his_doctor_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_tenant_id'), 'doctors', ['tenant_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('slot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('patient_phone', sa.String(length=30), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('his_booking_id', sa.String(length=100), nullable=True),
    sa.Column('call_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_doctors_tenant_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_call_logs_tenant_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_outcome'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_call_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
